![banner](../../docs/figs/brand_identity/banner.png)

## **NumPy Basics**

NumPy (Numerical Python) is a Python library used for fast numerical operations.

- It allows you to work with large arrays and matrices.
- It's much faster and more efficient than Python lists for math operations.
- It is the foundation for many scientific libraries in Python (like Pandas, Scikit-learn, etc).

#### Why not just use lists?
- Lists are flexible, but slow for large-scale calculations.
- NumPy arrays use less memory and support powerful vectorized operations (doing math on many values at once).

## 1. Array (list)

#### Array via `array`

In [20]:
# Import numpy
import numpy as np

# Create a NumPy array from a list
a = np.array([1, 2, 3, 4])
print("Array:", a)

Array: [1 2 3 4]


#### Array via `arange`

In [19]:
# range(start,stop,step)
for range_a in range(1,10,2):
    print(range_a)

1
3
5
7
9


In [3]:
# np.arange(start,stop,step)
range_a = np.arange(0,9,2)
print("Range array:", range_a)

Range array: [0 2 4 6 8]


#### Basic statistics

In [8]:
print("Mean:", np.mean(range_a))
print("Median:", np.median(range_a))
print("Sum:", np.sum(range_a))
print("Max:", np.max(range_a))
print("Min:", np.min(range_a))
print("+10:", range_a + 10)
print("x10:", range_a * 10)

Mean: 4.0
Median: 4.0
Sum: 20
Max: 8
Min: 0
+10: [10 12 14 16 18]
x10: [ 0 20 40 60 80]


## 2. Matrix (table)

#### Matrix via `array`

In [28]:
# 3x3 matrix
matrix = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])

print(matrix)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Matrix via `arange`

In [16]:
# 3x3 matrix
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# 3x3 matrix
matrix = np.arange(0,17,2).reshape(3, 3)

print(matrix)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


## Shape and dimension

#### 4D?!
<img src="../../docs/figs/w3/4d.png" width="80%">

In [28]:
data = np.arange(120).reshape(2,3,4,5)

# Data type (dtype): tells what kind of data the array holds
print("Data type:", data.dtype)

# Number of dimensions (ndim): tells how many axes or directions the array has
print("Number of dimensions:", data.ndim)

# Shape: size of each dimension (length along each axis)
print("Shape:", data.shape)

Data type: int32
Number of dimensions: 4
Shape: (2, 3, 4, 5)
